<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dein.ToolBox" Version="1.11.0" />
    <PackageReference Include="TextCopy" Version="6.2.1" />
  </ItemGroup>
</Project>
